# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_panGraphViewer(object):
    def setupUi(self, panGraphViewer):
        panGraphViewer.setObjectName("panGraphViewer")
        panGraphViewer.resize(1263, 976)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(panGraphViewer.sizePolicy().hasHeightForWidth())
        panGraphViewer.setSizePolicy(sizePolicy)
        panGraphViewer.setMinimumSize(QtCore.QSize(1200, 950))
        self.centralwidget = QtWidgets.QWidget(panGraphViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.plotFrame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotFrame.sizePolicy().hasHeightForWidth())
        self.plotFrame.setSizePolicy(sizePolicy)
        self.plotFrame.setMaximumSize(QtCore.QSize(410, 16777215))
        self.plotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrame.setObjectName("plotFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.plotFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plotGraphLayout = QtWidgets.QGridLayout()
        self.plotGraphLayout.setObjectName("plotGraphLayout")
        self.clearGraphPlot = QtWidgets.QPushButton(self.plotFrame)
        self.clearGraphPlot.setMinimumSize(QtCore.QSize(50, 23))
        self.clearGraphPlot.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clearGraphPlot.setObjectName("clearGraphPlot")
        self.plotGraphLayout.addWidget(self.clearGraphPlot, 0, 3, 1, 1)
        self.plotStatusLabel = QtWidgets.QLabel(self.plotFrame)
        self.plotStatusLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.plotStatusLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.plotStatusLabel.setObjectName("plotStatusLabel")
        self.plotGraphLayout.addWidget(self.plotStatusLabel, 0, 1, 1, 1)
        self.plotGraph = QtWidgets.QPushButton(self.plotFrame)
        self.plotGraph.setMinimumSize(QtCore.QSize(50, 23))
        self.plotGraph.setMaximumSize(QtCore.QSize(50, 16777215))
        self.plotGraph.setObjectName("plotGraph")
        self.plotGraphLayout.addWidget(self.plotGraph, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.plotFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.plotGraphLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.plotGraphLayout)
        self.gridLayout_2.addWidget(self.plotFrame, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.checkNodesFrame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkNodesFrame.sizePolicy().hasHeightForWidth())
        self.checkNodesFrame.setSizePolicy(sizePolicy)
        self.checkNodesFrame.setMaximumSize(QtCore.QSize(410, 16777215))
        self.checkNodesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.checkNodesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.checkNodesFrame.setObjectName("checkNodesFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.checkNodesFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.nodesLayout = QtWidgets.QGridLayout()
        self.nodesLayout.setObjectName("nodesLayout")
        self.rmSelectedNodes = QtWidgets.QPushButton(self.checkNodesFrame)
        self.rmSelectedNodes.setMinimumSize(QtCore.QSize(60, 23))
        self.rmSelectedNodes.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rmSelectedNodes.setObjectName("rmSelectedNodes")
        self.nodesLayout.addWidget(self.rmSelectedNodes, 0, 3, 1, 1)
        self.addNode = QtWidgets.QPushButton(self.checkNodesFrame)
        self.addNode.setMinimumSize(QtCore.QSize(50, 23))
        self.addNode.setMaximumSize(QtCore.QSize(50, 16777215))
        self.addNode.setObjectName("addNode")
        self.nodesLayout.addWidget(self.addNode, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.checkNodesFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.nodesLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.nodesComboBox = QtWidgets.QComboBox(self.checkNodesFrame)
        self.nodesComboBox.setMinimumSize(QtCore.QSize(0, 23))
        self.nodesComboBox.setMaximumSize(QtCore.QSize(110, 16777215))
        self.nodesComboBox.setObjectName("nodesComboBox")
        self.nodesLayout.addWidget(self.nodesComboBox, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.nodesLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem2)
        self.showSelectedNodesLayout = QtWidgets.QGridLayout()
        self.showSelectedNodesLayout.setObjectName("showSelectedNodesLayout")
        self.nodesListLayout = QtWidgets.QGridLayout()
        self.nodesListLayout.setObjectName("nodesListLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textEdit = QtWidgets.QTextEdit(self.checkNodesFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_7.addWidget(self.textEdit)
        self.nodesListLayout.addLayout(self.verticalLayout_7, 0, 0, 7, 1)
        self.checkNodesInfo = QtWidgets.QPushButton(self.checkNodesFrame)
        self.checkNodesInfo.setMinimumSize(QtCore.QSize(0, 23))
        self.checkNodesInfo.setObjectName("checkNodesInfo")
        self.nodesListLayout.addWidget(self.checkNodesInfo, 1, 1, 1, 1)
        self.clearNodeList = QtWidgets.QPushButton(self.checkNodesFrame)
        self.clearNodeList.setMinimumSize(QtCore.QSize(0, 23))
        self.clearNodeList.setObjectName("clearNodeList")
        self.nodesListLayout.addWidget(self.clearNodeList, 2, 1, 1, 1)
        self.saveNodesInfo = QtWidgets.QPushButton(self.checkNodesFrame)
        self.saveNodesInfo.setMinimumSize(QtCore.QSize(116, 23))
        self.saveNodesInfo.setObjectName("saveNodesInfo")
        self.nodesListLayout.addWidget(self.saveNodesInfo, 3, 1, 1, 1)
        self.nodeStatus = QtWidgets.QLabel(self.checkNodesFrame)
        self.nodeStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.nodeStatus.setObjectName("nodeStatus")
        self.nodesListLayout.addWidget(self.nodeStatus, 4, 1, 1, 1)
        self.showSelectedNodesLayout.addLayout(self.nodesListLayout, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.showSelectedNodesLayout)
        self.gridLayout_2.addWidget(self.checkNodesFrame, 5, 0, 1, 1)
        self.checkGeneOvlpFrame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkGeneOvlpFrame.sizePolicy().hasHeightForWidth())
        self.checkGeneOvlpFrame.setSizePolicy(sizePolicy)
        self.checkGeneOvlpFrame.setMaximumSize(QtCore.QSize(410, 16777215))
        self.checkGeneOvlpFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.checkGeneOvlpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.checkGeneOvlpFrame.setObjectName("checkGeneOvlpFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.checkGeneOvlpFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.checkGeneOvlpFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.annoLayout = QtWidgets.QGridLayout()
        self.annoLayout.setObjectName("annoLayout")
        self.bedPath = QtWidgets.QLineEdit(self.checkGeneOvlpFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bedPath.sizePolicy().hasHeightForWidth())
        self.bedPath.setSizePolicy(sizePolicy)
        self.bedPath.setMinimumSize(QtCore.QSize(0, 23))
        self.bedPath.setObjectName("bedPath")
        self.annoLayout.addWidget(self.bedPath, 2, 1, 1, 1)
        self.bedLabel = QtWidgets.QLabel(self.checkGeneOvlpFrame)
        self.bedLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.bedLabel.setObjectName("bedLabel")
        self.annoLayout.addWidget(self.bedLabel, 2, 0, 1, 1)
        self.clearBedPath = QtWidgets.QPushButton(self.checkGeneOvlpFrame)
        self.clearBedPath.setMinimumSize(QtCore.QSize(50, 23))
        self.clearBedPath.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clearBedPath.setObjectName("clearBedPath")
        self.annoLayout.addWidget(self.clearBedPath, 2, 3, 1, 1)
        self.selectBedPath = QtWidgets.QPushButton(self.checkGeneOvlpFrame)
        self.selectBedPath.setMinimumSize(QtCore.QSize(50, 23))
        self.selectBedPath.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selectBedPath.setObjectName("selectBedPath")
        self.annoLayout.addWidget(self.selectBedPath, 2, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.annoLayout)
        self.checkGeneOvlpLayout = QtWidgets.QGridLayout()
        self.checkGeneOvlpLayout.setObjectName("checkGeneOvlpLayout")
        self.parseGene = QtWidgets.QPushButton(self.checkGeneOvlpFrame)
        self.parseGene.setMinimumSize(QtCore.QSize(50, 23))
        self.parseGene.setMaximumSize(QtCore.QSize(50, 16777215))
        self.parseGene.setObjectName("parseGene")
        self.checkGeneOvlpLayout.addWidget(self.parseGene, 0, 3, 1, 1)
        self.geneLabel = QtWidgets.QLabel(self.checkGeneOvlpFrame)
        self.geneLabel.setObjectName("geneLabel")
        self.checkGeneOvlpLayout.addWidget(self.geneLabel, 0, 0, 1, 1)
        self.plotOvlplabel = QtWidgets.QLabel(self.checkGeneOvlpFrame)
        self.plotOvlplabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.plotOvlplabel.setObjectName("plotOvlplabel")
        self.checkGeneOvlpLayout.addWidget(self.plotOvlplabel, 1, 0, 1, 1)
        self.plotOvlap = QtWidgets.QPushButton(self.checkGeneOvlpFrame)
        self.plotOvlap.setMinimumSize(QtCore.QSize(50, 23))
        self.plotOvlap.setMaximumSize(QtCore.QSize(50, 16777215))
        self.plotOvlap.setObjectName("plotOvlap")
        self.checkGeneOvlpLayout.addWidget(self.plotOvlap, 1, 3, 1, 1)
        self.geneComboBox = QtWidgets.QComboBox(self.checkGeneOvlpFrame)
        self.geneComboBox.setMinimumSize(QtCore.QSize(0, 23))
        self.geneComboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.geneComboBox.setIconSize(QtCore.QSize(50, 16))
        self.geneComboBox.setObjectName("geneComboBox")
        self.checkGeneOvlpLayout.addWidget(self.geneComboBox, 1, 1, 1, 1)
        self.bedParseStatus = QtWidgets.QLabel(self.checkGeneOvlpFrame)
        self.bedParseStatus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bedParseStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bedParseStatus.setObjectName("bedParseStatus")
        self.checkGeneOvlpLayout.addWidget(self.bedParseStatus, 0, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.checkGeneOvlpLayout)
        self.gridLayout_2.addWidget(self.checkGeneOvlpFrame, 6, 0, 1, 1)
        self.loadGFAFrame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadGFAFrame.sizePolicy().hasHeightForWidth())
        self.loadGFAFrame.setSizePolicy(sizePolicy)
        self.loadGFAFrame.setMinimumSize(QtCore.QSize(410, 240))
        self.loadGFAFrame.setMaximumSize(QtCore.QSize(410, 500))
        self.loadGFAFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadGFAFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadGFAFrame.setObjectName("loadGFAFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.loadGFAFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkbox = QtWidgets.QLabel(self.loadGFAFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.checkbox.setFont(font)
        self.checkbox.setObjectName("checkbox")
        self.verticalLayout_3.addWidget(self.checkbox)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.loadGFAFrame)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(0, 185))
        self.tabWidget_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.rGFAtab = QtWidgets.QWidget()
        self.rGFAtab.setObjectName("rGFAtab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.rGFAtab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 40, 371, 111))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.outDirLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.outDirLayout.setContentsMargins(0, 0, 0, 0)
        self.outDirLayout.setObjectName("outDirLayout")
        self.selectOutPath = QtWidgets.QPushButton(self.layoutWidget_2)
        self.selectOutPath.setMinimumSize(QtCore.QSize(50, 25))
        self.selectOutPath.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selectOutPath.setObjectName("selectOutPath")
        self.outDirLayout.addWidget(self.selectOutPath, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.outDirLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_2.setObjectName("label_2")
        self.outDirLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.status = QtWidgets.QLabel(self.layoutWidget_2)
        self.status.setMinimumSize(QtCore.QSize(120, 25))
        self.status.setMaximumSize(QtCore.QSize(100, 16777215))
        self.status.setObjectName("status")
        self.outDirLayout.addWidget(self.status, 2, 1, 1, 1)
        self.outDirLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.outDirLabel.setMinimumSize(QtCore.QSize(105, 0))
        self.outDirLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.outDirLabel.setObjectName("outDirLabel")
        self.outDirLayout.addWidget(self.outDirLabel, 1, 0, 1, 1)
        self.gfaPath = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gfaPath.sizePolicy().hasHeightForWidth())
        self.gfaPath.setSizePolicy(sizePolicy)
        self.gfaPath.setMinimumSize(QtCore.QSize(0, 25))
        self.gfaPath.setObjectName("gfaPath")
        self.outDirLayout.addWidget(self.gfaPath, 0, 1, 1, 1)
        self.clearOutPath = QtWidgets.QPushButton(self.layoutWidget_2)
        self.clearOutPath.setMinimumSize(QtCore.QSize(50, 23))
        self.clearOutPath.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clearOutPath.setObjectName("clearOutPath")
        self.outDirLayout.addWidget(self.clearOutPath, 1, 3, 1, 1)
        self.outDirPath = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outDirPath.sizePolicy().hasHeightForWidth())
        self.outDirPath.setSizePolicy(sizePolicy)
        self.outDirPath.setMinimumSize(QtCore.QSize(0, 25))
        self.outDirPath.setObjectName("outDirPath")
        self.outDirLayout.addWidget(self.outDirPath, 1, 1, 1, 1)
        self.selectGFA = QtWidgets.QPushButton(self.layoutWidget_2)
        self.selectGFA.setMinimumSize(QtCore.QSize(50, 25))
        self.selectGFA.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selectGFA.setObjectName("selectGFA")
        self.outDirLayout.addWidget(self.selectGFA, 0, 2, 1, 1)
        self.startParseGFA = QtWidgets.QPushButton(self.layoutWidget_2)
        self.startParseGFA.setMinimumSize(QtCore.QSize(50, 25))
        self.startParseGFA.setMaximumSize(QtCore.QSize(50, 16777215))
        self.startParseGFA.setObjectName("startParseGFA")
        self.outDirLayout.addWidget(self.startParseGFA, 2, 3, 1, 1)
        self.clearGFA = QtWidgets.QPushButton(self.layoutWidget_2)
        self.clearGFA.setMinimumSize(QtCore.QSize(50, 25))
        self.clearGFA.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clearGFA.setObjectName("clearGFA")
        self.outDirLayout.addWidget(self.clearGFA, 0, 3, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.rGFAtab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 371, 27))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.rGFAtab, "")
        self.VCFtab = QtWidgets.QWidget()
        self.VCFtab.setObjectName("VCFtab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.VCFtab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vcfSelect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.vcfSelect.setMinimumSize(QtCore.QSize(0, 25))
        self.vcfSelect.setMaximumSize(QtCore.QSize(50, 16777215))
        self.vcfSelect.setObjectName("vcfSelect")
        self.gridLayout.addWidget(self.vcfSelect, 1, 2, 1, 1)
        self.outDirClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.outDirClear.setMinimumSize(QtCore.QSize(50, 25))
        self.outDirClear.setMaximumSize(QtCore.QSize(50, 16777215))
        self.outDirClear.setObjectName("outDirClear")
        self.gridLayout.addWidget(self.outDirClear, 2, 3, 1, 1)
        self.outDirSelect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.outDirSelect.setMinimumSize(QtCore.QSize(50, 25))
        self.outDirSelect.setMaximumSize(QtCore.QSize(50, 16777215))
        self.outDirSelect.setObjectName("outDirSelect")
        self.gridLayout.addWidget(self.outDirSelect, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 22))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.bbName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bbName.setMinimumSize(QtCore.QSize(0, 25))
        self.bbName.setText("")
        self.bbName.setObjectName("bbName")
        self.gridLayout.addWidget(self.bbName, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.statusVCF = QtWidgets.QLabel(self.gridLayoutWidget)
        self.statusVCF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusVCF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.statusVCF.setObjectName("statusVCF")
        self.gridLayout.addWidget(self.statusVCF, 5, 1, 1, 1)
        self.parseVCF = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.parseVCF.setMinimumSize(QtCore.QSize(0, 25))
        self.parseVCF.setMaximumSize(QtCore.QSize(50, 16777215))
        self.parseVCF.setObjectName("parseVCF")
        self.gridLayout.addWidget(self.parseVCF, 5, 3, 1, 1)
        self.vcfClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.vcfClear.setMinimumSize(QtCore.QSize(0, 25))
        self.vcfClear.setMaximumSize(QtCore.QSize(50, 16777215))
        self.vcfClear.setObjectName("vcfClear")
        self.gridLayout.addWidget(self.vcfClear, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.outDir = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.outDir.setMinimumSize(QtCore.QSize(0, 25))
        self.outDir.setObjectName("outDir")
        self.gridLayout.addWidget(self.outDir, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(0, 25))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.threads = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.threads.setMinimumSize(QtCore.QSize(0, 25))
        self.threads.setMaximumSize(QtCore.QSize(50, 16777215))
        self.threads.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.threads.setObjectName("threads")
        self.gridLayout.addWidget(self.threads, 3, 3, 1, 1)
        self.vcfPath = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.vcfPath.setMinimumSize(QtCore.QSize(0, 25))
        self.vcfPath.setObjectName("vcfPath")
        self.gridLayout.addWidget(self.vcfPath, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.fastaPath = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fastaPath.setMinimumSize(QtCore.QSize(0, 25))
        self.fastaPath.setObjectName("fastaPath")
        self.gridLayout.addWidget(self.fastaPath, 4, 1, 1, 1)
        self.fastaSelect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.fastaSelect.setMinimumSize(QtCore.QSize(0, 25))
        self.fastaSelect.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fastaSelect.setObjectName("fastaSelect")
        self.gridLayout.addWidget(self.fastaSelect, 4, 2, 1, 1)
        self.fastaClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.fastaClear.setMinimumSize(QtCore.QSize(0, 25))
        self.fastaClear.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fastaClear.setObjectName("fastaClear")
        self.gridLayout.addWidget(self.fastaClear, 4, 3, 1, 1)
        self.tabWidget_2.addTab(self.VCFtab, "")
        self.verticalLayout_3.addWidget(self.tabWidget_2)
        self.gridLayout_2.addWidget(self.loadGFAFrame, 2, 0, 1, 1)
        self.vizCanvas = QtWidgets.QTabWidget(self.widget)
        self.vizCanvas.setTabPosition(QtWidgets.QTabWidget.North)
        self.vizCanvas.setElideMode(QtCore.Qt.ElideNone)
        self.vizCanvas.setTabsClosable(True)
        self.vizCanvas.setObjectName("vizCanvas")
        self.gridLayout_2.addWidget(self.vizCanvas, 0, 1, 8, 1)
        self.ParameterFrame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ParameterFrame.sizePolicy().hasHeightForWidth())
        self.ParameterFrame.setSizePolicy(sizePolicy)
        self.ParameterFrame.setMinimumSize(QtCore.QSize(410, 220))
        self.ParameterFrame.setMaximumSize(QtCore.QSize(410, 250))
        self.ParameterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ParameterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ParameterFrame.setObjectName("ParameterFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ParameterFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.ParameterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.tabWidget = QtWidgets.QTabWidget(self.ParameterFrame)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 180))
        self.tabWidget.setMaximumSize(QtCore.QSize(400, 180))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 371, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.parameteLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.parameteLayout_4.setContentsMargins(0, 0, 0, 0)
        self.parameteLayout_4.setObjectName("parameteLayout_4")
        self.comboBoxSample = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSample.sizePolicy().hasHeightForWidth())
        self.comboBoxSample.setSizePolicy(sizePolicy)
        self.comboBoxSample.setMinimumSize(QtCore.QSize(90, 23))
        self.comboBoxSample.setMaximumSize(QtCore.QSize(90, 16777215))
        self.comboBoxSample.setObjectName("comboBoxSample")
        self.parameteLayout_4.addWidget(self.comboBoxSample, 0, 2, 1, 1)
        self.startLabel_4 = QtWidgets.QLabel(self.layoutWidget)
        self.startLabel_4.setObjectName("startLabel_4")
        self.parameteLayout_4.addWidget(self.startLabel_4, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.parameteLayout_4.addItem(spacerItem3, 0, 1, 1, 1)
        self.endPosition = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endPosition.sizePolicy().hasHeightForWidth())
        self.endPosition.setSizePolicy(sizePolicy)
        self.endPosition.setMinimumSize(QtCore.QSize(90, 23))
        self.endPosition.setMaximumSize(QtCore.QSize(90, 16777215))
        self.endPosition.setObjectName("endPosition")
        self.parameteLayout_4.addWidget(self.endPosition, 3, 2, 1, 1)
        self.chrLabel_4 = QtWidgets.QLabel(self.layoutWidget)
        self.chrLabel_4.setObjectName("chrLabel_4")
        self.parameteLayout_4.addWidget(self.chrLabel_4, 1, 0, 1, 1)
        self.backboneLabel_4 = QtWidgets.QLabel(self.layoutWidget)
        self.backboneLabel_4.setObjectName("backboneLabel_4")
        self.parameteLayout_4.addWidget(self.backboneLabel_4, 0, 0, 1, 1)
        self.endLabel_4 = QtWidgets.QLabel(self.layoutWidget)
        self.endLabel_4.setObjectName("endLabel_4")
        self.parameteLayout_4.addWidget(self.endLabel_4, 3, 0, 1, 1)
        self.startPosition = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startPosition.sizePolicy().hasHeightForWidth())
        self.startPosition.setSizePolicy(sizePolicy)
        self.startPosition.setMinimumSize(QtCore.QSize(90, 23))
        self.startPosition.setMaximumSize(QtCore.QSize(90, 16777215))
        self.startPosition.setObjectName("startPosition")
        self.parameteLayout_4.addWidget(self.startPosition, 2, 2, 1, 1)
        self.comboBoxChr = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxChr.sizePolicy().hasHeightForWidth())
        self.comboBoxChr.setSizePolicy(sizePolicy)
        self.comboBoxChr.setMinimumSize(QtCore.QSize(90, 23))
        self.comboBoxChr.setMaximumSize(QtCore.QSize(90, 16777215))
        self.comboBoxChr.setObjectName("comboBoxChr")
        self.parameteLayout_4.addWidget(self.comboBoxChr, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 10, 381, 141))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.nodesListLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.nodesListLayout_2.setContentsMargins(0, 0, 0, 0)
        self.nodesListLayout_2.setObjectName("nodesListLayout_2")
        self.removeSample = QtWidgets.QPushButton(self.layoutWidget_3)
        self.removeSample.setMinimumSize(QtCore.QSize(0, 23))
        self.removeSample.setObjectName("removeSample")
        self.nodesListLayout_2.addWidget(self.removeSample, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_6.setMinimumSize(QtCore.QSize(116, 18))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.nodesListLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.ResetSamples = QtWidgets.QPushButton(self.layoutWidget_3)
        self.ResetSamples.setMinimumSize(QtCore.QSize(116, 23))
        self.ResetSamples.setObjectName("ResetSamples")
        self.nodesListLayout_2.addWidget(self.ResetSamples, 4, 2, 1, 1)
        self.AddBackSample = QtWidgets.QPushButton(self.layoutWidget_3)
        self.AddBackSample.setMinimumSize(QtCore.QSize(0, 23))
        self.AddBackSample.setObjectName("AddBackSample")
        self.nodesListLayout_2.addWidget(self.AddBackSample, 3, 2, 1, 1)
        self.sampleComboBox = QtWidgets.QComboBox(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleComboBox.sizePolicy().hasHeightForWidth())
        self.sampleComboBox.setSizePolicy(sizePolicy)
        self.sampleComboBox.setMinimumSize(QtCore.QSize(0, 23))
        self.sampleComboBox.setMaximumSize(QtCore.QSize(116, 16777215))
        self.sampleComboBox.setObjectName("sampleComboBox")
        self.nodesListLayout_2.addWidget(self.sampleComboBox, 1, 2, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 80))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 130))
        self.textEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_8.addWidget(self.textEdit_2)
        self.nodesListLayout_2.addLayout(self.verticalLayout_8, 0, 1, 7, 1)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.nodesListLayout_2.addItem(spacerItem4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.gridLayout_2.addWidget(self.ParameterFrame, 3, 0, 1, 1)
        self.softwareLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.softwareLabel.setFont(font)
        self.softwareLabel.setObjectName("softwareLabel")
        self.gridLayout_2.addWidget(self.softwareLabel, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        panGraphViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(panGraphViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1263, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuVCF_to_GFA = QtWidgets.QMenu(self.menuAnalysis)
        self.menuVCF_to_GFA.setObjectName("menuVCF_to_GFA")
        self.menuOnline_checking = QtWidgets.QMenu(self.menuAnalysis)
        self.menuOnline_checking.setObjectName("menuOnline_checking")
        self.menuScreenshot = QtWidgets.QMenu(self.menuAnalysis)
        self.menuScreenshot.setObjectName("menuScreenshot")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        panGraphViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(panGraphViewer)
        self.statusbar.setObjectName("statusbar")
        panGraphViewer.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(panGraphViewer)
        self.actionNew.setObjectName("actionNew")
        self.actionClose = QtWidgets.QAction(panGraphViewer)
        self.actionClose.setObjectName("actionClose")
        self.actionMultiple_Sequence_Alignment = QtWidgets.QAction(panGraphViewer)
        self.actionMultiple_Sequence_Alignment.setObjectName("actionMultiple_Sequence_Alignment")
        self.actionDNA_sequences_and_overlap_protein_check = QtWidgets.QAction(panGraphViewer)
        self.actionDNA_sequences_and_overlap_protein_check.setObjectName("actionDNA_sequences_and_overlap_protein_check")
        self.actionAbout = QtWidgets.QAction(panGraphViewer)
        self.actionAbout.setObjectName("actionAbout")
        self.actionManual = QtWidgets.QAction(panGraphViewer)
        self.actionManual.setObjectName("actionManual")
        self.actionFeedback = QtWidgets.QAction(panGraphViewer)
        self.actionFeedback.setObjectName("actionFeedback")
        self.actionGFA1_to_GFA2 = QtWidgets.QAction(panGraphViewer)
        self.actionGFA1_to_GFA2.setObjectName("actionGFA1_to_GFA2")
        self.actionVCF_to_rGFA = QtWidgets.QAction(panGraphViewer)
        self.actionVCF_to_rGFA.setObjectName("actionVCF_to_rGFA")
        self.actionNCBI_Blast = QtWidgets.QAction(panGraphViewer)
        self.actionNCBI_Blast.setObjectName("actionNCBI_Blast")
        self.actionMSA = QtWidgets.QAction(panGraphViewer)
        self.actionMSA.setObjectName("actionMSA")
        self.actionContact_the_Author = QtWidgets.QAction(panGraphViewer)
        self.actionContact_the_Author.setObjectName("actionContact_the_Author")
        self.actionNode_Shapes = QtWidgets.QAction(panGraphViewer)
        self.actionNode_Shapes.setObjectName("actionNode_Shapes")
        self.actionGraph_modification = QtWidgets.QAction(panGraphViewer)
        self.actionGraph_modification.setObjectName("actionGraph_modification")
        self.actionModify_FASTA_header = QtWidgets.QAction(panGraphViewer)
        self.actionModify_FASTA_header.setObjectName("actionModify_FASTA_header")
        self.actionUpdate = QtWidgets.QAction(panGraphViewer)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionPrimary_Screen_Clipping = QtWidgets.QAction(panGraphViewer)
        self.actionPrimary_Screen_Clipping.setObjectName("actionPrimary_Screen_Clipping")
        self.actionFull_Screen_s_Capturing = QtWidgets.QAction(panGraphViewer)
        self.actionFull_Screen_s_Capturing.setObjectName("actionFull_Screen_s_Capturing")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionClose)
        self.menuVCF_to_GFA.addAction(self.actionVCF_to_rGFA)
        self.menuVCF_to_GFA.addAction(self.actionModify_FASTA_header)
        self.menuOnline_checking.addAction(self.actionNCBI_Blast)
        self.menuOnline_checking.addAction(self.actionMSA)
        self.menuScreenshot.addAction(self.actionPrimary_Screen_Clipping)
        self.menuScreenshot.addAction(self.actionFull_Screen_s_Capturing)
        self.menuAnalysis.addAction(self.menuVCF_to_GFA.menuAction())
        self.menuAnalysis.addAction(self.menuOnline_checking.menuAction())
        self.menuAnalysis.addAction(self.menuScreenshot.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionFeedback)
        self.menuHelp.addAction(self.actionUpdate)
        self.menuHelp.addAction(self.actionContact_the_Author)
        self.menuSettings.addAction(self.actionNode_Shapes)
        self.menuSettings.addAction(self.actionGraph_modification)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(panGraphViewer)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(panGraphViewer)

    def retranslateUi(self, panGraphViewer):
        _translate = QtCore.QCoreApplication.translate
        panGraphViewer.setWindowTitle(_translate("panGraphViewer", "panGraphViewer"))
        self.clearGraphPlot.setText(_translate("panGraphViewer", "Clear"))
        self.plotStatusLabel.setText(_translate("panGraphViewer", "Idle"))
        self.plotGraph.setText(_translate("panGraphViewer", "Plot"))
        self.label_12.setText(_translate("panGraphViewer", "Plot the Graph"))
        self.rmSelectedNodes.setText(_translate("panGraphViewer", "Remove"))
        self.addNode.setText(_translate("panGraphViewer", "Add"))
        self.label_13.setText(_translate("panGraphViewer", "Available Nodes"))
        self.textEdit.setHtml(_translate("panGraphViewer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#d1d1d1;\">List of the selected node(s)</span></p></body></html>"))
        self.checkNodesInfo.setText(_translate("panGraphViewer", "Check"))
        self.clearNodeList.setText(_translate("panGraphViewer", "Clear "))
        self.saveNodesInfo.setText(_translate("panGraphViewer", "Save the Sequences"))
        self.nodeStatus.setText(_translate("panGraphViewer", "Idle"))
        self.label_14.setText(_translate("panGraphViewer", "Nodes Overlap with Genes"))
        self.bedLabel.setText(_translate("panGraphViewer", "The annotation file"))
        self.clearBedPath.setText(_translate("panGraphViewer", "Clear"))
        self.selectBedPath.setText(_translate("panGraphViewer", "Select"))
        self.parseGene.setText(_translate("panGraphViewer", "Start"))
        self.geneLabel.setText(_translate("panGraphViewer", "Parse the annotation file and link nodes to genes"))
        self.plotOvlplabel.setText(_translate("panGraphViewer", "Node(s) overlapping with Gene: "))
        self.plotOvlap.setText(_translate("panGraphViewer", "Plot"))
        self.bedParseStatus.setText(_translate("panGraphViewer", "Idle"))
        self.checkbox.setText(_translate("panGraphViewer", "Load File(s) for Graph Visualization"))
        self.selectOutPath.setText(_translate("panGraphViewer", "Select"))
        self.label_8.setText(_translate("panGraphViewer", "Parse GFA"))
        self.label_2.setText(_translate("panGraphViewer", "The GFA File"))
        self.status.setText(_translate("panGraphViewer", "Idle"))
        self.outDirLabel.setText(_translate("panGraphViewer", "Output Directory"))
        self.clearOutPath.setText(_translate("panGraphViewer", "Clear"))
        self.selectGFA.setText(_translate("panGraphViewer", "Select"))
        self.startParseGFA.setText(_translate("panGraphViewer", "Start"))
        self.clearGFA.setText(_translate("panGraphViewer", "Clear"))
        self.label_10.setText(_translate("panGraphViewer", " (Reference) Graphical Fragment Assembly (GFA) File"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.rGFAtab), _translate("panGraphViewer", "GFA"))
        self.vcfSelect.setText(_translate("panGraphViewer", "Select"))
        self.outDirClear.setText(_translate("panGraphViewer", "Clear"))
        self.outDirSelect.setText(_translate("panGraphViewer", "Select"))
        self.label_4.setText(_translate("panGraphViewer", "Output Directory"))
        self.label_5.setText(_translate("panGraphViewer", "Bacbone name"))
        self.label_3.setText(_translate("panGraphViewer", "The VCF File"))
        self.statusVCF.setText(_translate("panGraphViewer", "Idle"))
        self.parseVCF.setText(_translate("panGraphViewer", "Start"))
        self.vcfClear.setText(_translate("panGraphViewer", "Clear"))
        self.label_7.setText(_translate("panGraphViewer", "Parse VCF"))
        self.label_9.setText(_translate("panGraphViewer", "Threads"))
        self.threads.setText(_translate("panGraphViewer", "4"))
        self.label.setText(_translate("panGraphViewer", "The Backbone Fasta"))
        self.fastaSelect.setText(_translate("panGraphViewer", "Select"))
        self.fastaClear.setText(_translate("panGraphViewer", "Clear"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VCFtab), _translate("panGraphViewer", "VCF"))
        self.label_11.setText(_translate("panGraphViewer", "Selection for Plot"))
        self.startLabel_4.setText(_translate("panGraphViewer", "Start Position "))
        self.chrLabel_4.setText(_translate("panGraphViewer", "The chromosome/sequence to check"))
        self.backboneLabel_4.setText(_translate("panGraphViewer", "The backbone sample used in the panGraph"))
        self.endLabel_4.setText(_translate("panGraphViewer", "End Position"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("panGraphViewer", "Basic settings "))
        self.removeSample.setText(_translate("panGraphViewer", "Remove"))
        self.label_6.setText(_translate("panGraphViewer", "Sample"))
        self.ResetSamples.setText(_translate("panGraphViewer", "Reset"))
        self.AddBackSample.setText(_translate("panGraphViewer", "Add"))
        self.textEdit_2.setHtml(_translate("panGraphViewer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#d1d1d1;\">Samples that want to be included </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("panGraphViewer", "Sample(s) showing"))
        self.softwareLabel.setText(_translate("panGraphViewer", "PanGraphViewer"))
        self.menuFile.setTitle(_translate("panGraphViewer", "File"))
        self.menuAnalysis.setTitle(_translate("panGraphViewer", "Tools"))
        self.menuVCF_to_GFA.setTitle(_translate("panGraphViewer", "Format Conversion"))
        self.menuOnline_checking.setTitle(_translate("panGraphViewer", "Online Sequence Checking"))
        self.menuScreenshot.setTitle(_translate("panGraphViewer", "Screenshot"))
        self.menuHelp.setTitle(_translate("panGraphViewer", "Help"))
        self.menuSettings.setTitle(_translate("panGraphViewer", "Settings"))
        self.actionNew.setText(_translate("panGraphViewer", "New Project"))
        self.actionNew.setShortcut(_translate("panGraphViewer", "Ctrl+N"))
        self.actionClose.setText(_translate("panGraphViewer", "Exit "))
        self.actionClose.setShortcut(_translate("panGraphViewer", "Ctrl+Q"))
        self.actionMultiple_Sequence_Alignment.setText(_translate("panGraphViewer", "Online multiple sequence alignment"))
        self.actionDNA_sequences_and_overlap_protein_check.setText(_translate("panGraphViewer", "DNA sequences and overlap protein check"))
        self.actionAbout.setText(_translate("panGraphViewer", "About  panGraphViewer"))
        self.actionAbout.setShortcut(_translate("panGraphViewer", "Ctrl+A"))
        self.actionManual.setText(_translate("panGraphViewer", "Manual"))
        self.actionFeedback.setText(_translate("panGraphViewer", "Report A Bug ..."))
        self.actionFeedback.setShortcut(_translate("panGraphViewer", "Ctrl+R"))
        self.actionGFA1_to_GFA2.setText(_translate("panGraphViewer", "GFA_v1 to GFA_v2"))
        self.actionVCF_to_rGFA.setText(_translate("panGraphViewer", "VCF to rGFA"))
        self.actionNCBI_Blast.setText(_translate("panGraphViewer", "NCBI-Blast"))
        self.actionMSA.setText(_translate("panGraphViewer", "Multiple Sequence Alignment"))
        self.actionContact_the_Author.setText(_translate("panGraphViewer", "Contact the Author"))
        self.actionContact_the_Author.setShortcut(_translate("panGraphViewer", "Ctrl+S"))
        self.actionNode_Shapes.setText(_translate("panGraphViewer", "Node Shapes"))
        self.actionGraph_modification.setText(_translate("panGraphViewer", "Graph Modification"))
        self.actionModify_FASTA_header.setText(_translate("panGraphViewer", "Modify FASTA Header"))
        self.actionUpdate.setText(_translate("panGraphViewer", "Update"))
        self.actionPrimary_Screen_Clipping.setText(_translate("panGraphViewer", "Primary Screen Clipping"))
        self.actionFull_Screen_s_Capturing.setText(_translate("panGraphViewer", "Full Screen(s) Capturing"))
