# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraphModification.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphModi(object):
    def setupUi(self, GraphModi):
        GraphModi.setObjectName("GraphModi")
        GraphModi.resize(380, 390)
        GraphModi.setMinimumSize(QtCore.QSize(380, 390))
        GraphModi.setMaximumSize(QtCore.QSize(380, 390))
        self.label = QtWidgets.QLabel(GraphModi)
        self.label.setGeometry(QtCore.QRect(10, 10, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(GraphModi)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 357, 269))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.threshold = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.threshold.setMinimumSize(QtCore.QSize(0, 25))
        self.threshold.setObjectName("threshold")
        self.gridLayout.addWidget(self.threshold, 7, 2, 1, 1)
        self.interaction = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.interaction.setMinimumSize(QtCore.QSize(0, 25))
        self.interaction.setMaximumSize(QtCore.QSize(80, 16777215))
        self.interaction.setObjectName("interaction")
        self.interaction.addItem("")
        self.interaction.addItem("")
        self.gridLayout.addWidget(self.interaction, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.height = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.height.setMinimumSize(QtCore.QSize(0, 25))
        self.height.setMaximumSize(QtCore.QSize(80, 16777215))
        self.height.setObjectName("height")
        self.gridLayout.addWidget(self.height, 3, 2, 1, 1)
        self.width = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.width.setMinimumSize(QtCore.QSize(0, 25))
        self.width.setMaximumSize(QtCore.QSize(80, 16777215))
        self.width.setObjectName("width")
        self.gridLayout.addWidget(self.width, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 25))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(0, 25))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(255, 25))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.maxNodesDisplay = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.maxNodesDisplay.setMinimumSize(QtCore.QSize(0, 25))
        self.maxNodesDisplay.setMaximumSize(QtCore.QSize(80, 16777215))
        self.maxNodesDisplay.setObjectName("maxNodesDisplay")
        self.gridLayout.addWidget(self.maxNodesDisplay, 5, 2, 1, 1)
        self.layoutModification = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.layoutModification.setMinimumSize(QtCore.QSize(0, 25))
        self.layoutModification.setMaximumSize(QtCore.QSize(80, 16777215))
        self.layoutModification.setObjectName("layoutModification")
        self.layoutModification.addItem("")
        self.layoutModification.addItem("")
        self.gridLayout.addWidget(self.layoutModification, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(160, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.nodeLen = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nodeLen.setMinimumSize(QtCore.QSize(0, 25))
        self.nodeLen.setMaximumSize(QtCore.QSize(80, 16777215))
        self.nodeLen.setObjectName("nodeLen")
        self.gridLayout.addWidget(self.nodeLen, 6, 2, 1, 1)
        self.addRemoveNodes = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.addRemoveNodes.setMinimumSize(QtCore.QSize(0, 25))
        self.addRemoveNodes.setMaximumSize(QtCore.QSize(80, 16777215))
        self.addRemoveNodes.setObjectName("addRemoveNodes")
        self.addRemoveNodes.addItem("")
        self.addRemoveNodes.addItem("")
        self.gridLayout.addWidget(self.addRemoveNodes, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(GraphModi)
        self.pushButton.setGeometry(QtCore.QRect(250, 170, 0, 25))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(0, 25))
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(GraphModi)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 320, 361, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.reset = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.reset.setMinimumSize(QtCore.QSize(0, 25))
        self.reset.setMaximumSize(QtCore.QSize(50, 16777215))
        self.reset.setObjectName("reset")
        self.gridLayout_2.addWidget(self.reset, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setMinimumSize(QtCore.QSize(220, 25))
        self.label_7.setMaximumSize(QtCore.QSize(215, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.change = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.change.setMinimumSize(QtCore.QSize(0, 25))
        self.change.setMaximumSize(QtCore.QSize(50, 16777215))
        self.change.setObjectName("change")
        self.gridLayout_2.addWidget(self.change, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)

        self.retranslateUi(GraphModi)
        QtCore.QMetaObject.connectSlotsByName(GraphModi)

    def retranslateUi(self, GraphModi):
        _translate = QtCore.QCoreApplication.translate
        GraphModi.setWindowTitle(_translate("GraphModi", "Graph Modification"))
        self.label.setText(_translate("GraphModi", "Graph Modification for vis.js Graph"))
        self.threshold.setText(_translate("GraphModi", "2"))
        self.interaction.setItemText(0, _translate("GraphModi", "No"))
        self.interaction.setItemText(1, _translate("GraphModi", "Yes"))
        self.label_3.setText(_translate("GraphModi", "Enable layout modification"))
        self.label_5.setText(_translate("GraphModi", "Canvas height"))
        self.height.setText(_translate("GraphModi", "980"))
        self.width.setText(_translate("GraphModi", "1400"))
        self.label_8.setText(_translate("GraphModi", "Max num. of nodes to display"))
        self.label_9.setText(_translate("GraphModi", "Max length of seq to display (bp)"))
        self.label_4.setText(_translate("GraphModi", "Enable add/remove node"))
        self.label_10.setText(_translate("GraphModi", "Min num. of node overlapping with a gene  "))
        self.label_6.setText(_translate("GraphModi", "Canvas width"))
        self.maxNodesDisplay.setText(_translate("GraphModi", "200"))
        self.layoutModification.setItemText(0, _translate("GraphModi", "No"))
        self.layoutModification.setItemText(1, _translate("GraphModi", "Yes"))
        self.label_2.setText(_translate("GraphModi", "Enable interaction"))
        self.nodeLen.setText(_translate("GraphModi", "1000000"))
        self.addRemoveNodes.setItemText(0, _translate("GraphModi", "No"))
        self.addRemoveNodes.setItemText(1, _translate("GraphModi", "Yes"))
        self.pushButton.setText(_translate("GraphModi", "OK"))
        self.reset.setText(_translate("GraphModi", "Reset"))
        self.label_7.setText(_translate("GraphModi", "Do you want to keep the changes?"))
        self.change.setText(_translate("GraphModi", "Yes"))
