# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renameFastaHeader.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_header(object):
    def setupUi(self, header):
        header.setObjectName("header")
        header.resize(440, 245)
        header.setMinimumSize(QtCore.QSize(440, 245))
        header.setMaximumSize(QtCore.QSize(440, 245))
        self.gridLayoutWidget = QtWidgets.QWidget(header)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 421, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.outDirSelect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.outDirSelect.setMinimumSize(QtCore.QSize(0, 25))
        self.outDirSelect.setMaximumSize(QtCore.QSize(50, 16777215))
        self.outDirSelect.setObjectName("outDirSelect")
        self.gridLayout.addWidget(self.outDirSelect, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.fastaPath = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fastaPath.setMinimumSize(QtCore.QSize(0, 25))
        self.fastaPath.setObjectName("fastaPath")
        self.gridLayout.addWidget(self.fastaPath, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.outDir = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.outDir.setMinimumSize(QtCore.QSize(0, 25))
        self.outDir.setObjectName("outDir")
        self.gridLayout.addWidget(self.outDir, 1, 1, 1, 1)
        self.outDirClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.outDirClear.setMinimumSize(QtCore.QSize(0, 25))
        self.outDirClear.setMaximumSize(QtCore.QSize(50, 16777215))
        self.outDirClear.setObjectName("outDirClear")
        self.gridLayout.addWidget(self.outDirClear, 1, 3, 1, 1)
        self.fastaClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.fastaClear.setMinimumSize(QtCore.QSize(0, 25))
        self.fastaClear.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fastaClear.setObjectName("fastaClear")
        self.gridLayout.addWidget(self.fastaClear, 0, 3, 1, 1)
        self.fastaSelect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.fastaSelect.setMinimumSize(QtCore.QSize(50, 25))
        self.fastaSelect.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fastaSelect.setObjectName("fastaSelect")
        self.gridLayout.addWidget(self.fastaSelect, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(header)
        self.label.setGeometry(QtCore.QRect(10, 10, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(header)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 140, 421, 89))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sampleName = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.sampleName.setMinimumSize(QtCore.QSize(0, 25))
        self.sampleName.setMaximumSize(QtCore.QSize(105, 16777215))
        self.sampleName.setObjectName("sampleName")
        self.gridLayout_2.addWidget(self.sampleName, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.delim = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.delim.setMinimumSize(QtCore.QSize(0, 25))
        self.delim.setMaximumSize(QtCore.QSize(105, 16777215))
        self.delim.setObjectName("delim")
        self.gridLayout_2.addWidget(self.delim, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.startRename = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.startRename.setMinimumSize(QtCore.QSize(0, 25))
        self.startRename.setObjectName("startRename")
        self.gridLayout_2.addWidget(self.startRename, 2, 2, 1, 1)
        self.renameStatus = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.renameStatus.setMinimumSize(QtCore.QSize(0, 25))
        self.renameStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.renameStatus.setObjectName("renameStatus")
        self.gridLayout_2.addWidget(self.renameStatus, 2, 1, 1, 1)

        self.retranslateUi(header)
        QtCore.QMetaObject.connectSlotsByName(header)

    def retranslateUi(self, header):
        _translate = QtCore.QCoreApplication.translate
        header.setWindowTitle(_translate("header", "renameFastaHeader"))
        self.outDirSelect.setText(_translate("header", "Select"))
        self.label_2.setText(_translate("header", "The fasta file"))
        self.label_5.setText(_translate("header", "The output Directory"))
        self.outDirClear.setText(_translate("header", "Clear"))
        self.fastaClear.setText(_translate("header", "Clear"))
        self.fastaSelect.setText(_translate("header", "Select"))
        self.label.setText(_translate("header", "Rename the hearder of a given fasta file"))
        self.label_3.setText(_translate("header", "Name of the sample"))
        self.label_4.setText(_translate("header", "Delimiter "))
        self.delim.setText(_translate("header", "||"))
        self.label_6.setText(_translate("header", "Rename"))
        self.startRename.setText(_translate("header", "Start"))
        self.renameStatus.setText(_translate("header", "Idle"))
